### ISSUE TITLE
Limiting cache size per node

### ISSUE THREAD

**Issue by innerop** [NVIDIA/dfcpub#62]
Hi,

Let’s say I wish to limit the amount of space I used on local disk per machine. Where do i configure that?

**Comment by VirrageS** [comment]
The closest thing you can do, to limit the amount of space used, is to configure LRU (eviction system) [config](https://github.com/NVIDIA/dfcpub/blob/master/dfc/setup/config.sh#L39-L46):
```json
	"lru_config": {
		"lowwm":		75,
		"highwm":		90,
		"atime_cache_max":	65536,
		"dont_evict_time":	"120m",
		"capacity_upd_time":	"10m",
		"lru_enabled":  	true
	},
```

more info: https://github.com/NVIDIA/dfcpub#lru

Hope that helps, if you have any other questions let us know.
