### ISSUE TITLE
There is an info about what dfcpub is, but not why

### ISSUE THREAD

**Issue by mkevac** [NVIDIA/dfcpub#64]
I find it very difficult to understand why would one need dfcpub.
Documentation (README) lacks any examples and use cases.

**Comment by VirrageS** [comment]
Thanks for pointing that out! Our README needs a little bit of restructuring. In meantime we will try to improve it and add more sections like "Why DFC?".

**Comment by alex-aizman** [comment]
planning to release 2.0 by mid/end Jan. The "what" part then hopefully become clear enough...
